"""
Django settings for obras_particulares project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '68zfnz=4i8wkv(n6*n+*=*2+lybbps#b6v)z@+6gt2a2o7op@u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'persona',
    'tipos',
    'tramite',
    'documento',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'obras_particulares.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, 'templates') ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'obras_particulares.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Messages tags
from django.contrib import messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# Excel readers
FILE_UPLOAD_HANDLERS = ("django_excel.ExcelMemoryFileUploadHandler",
                        "django_excel.TemporaryExcelFileUploadHandler")


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTH_PASSWORD_VALIDATORS = []

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'es-AR'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static/')]
CRISPY_TEMPLATE_PACK = 'bootstrap3'
AUTH_USER_MODEL='persona.Usuario'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Para el envio de email

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Host for sending e-mail.
EMAIL_HOST = 'smtp.gmail.com'

# Port for sending e-mail.
EMAIL_PORT = 25

# Optional SMTP authentication information for EMAIL_HOST.
EMAIL_HOST_USER = 'infosopunpsjb@gmail.com'
EMAIL_HOST_PASSWORD = 'unpsjb2016'
EMAIL_USE_TLS = True


##############################################################
#####              D O C U M E N T A C I O N             #####
##############################################################

def acceso(user):
    try:
        if user.groups.filter(name='propietario'):
            return 1
        elif user.groups.filter(name='profesional'):
            return 2
        elif user.groups.filter(name='administrativo'):
            return 3
        elif user.groups.filter(name='visador'):
            return 4
        elif user.groups.filter(name='inspector'):
            return 5
        elif user.groups.filter(name='director'):
            return 6
        elif user.groups.filter(name='jefeinspector'):
            return 7
    except AttributeError:
        return 0



DOCUMENTATION_ACCESS_FUNCTION = acceso

DOCUMENTATION_ROOT_PROPIETARIO = os.path.join(BASE_DIR, 'documentacion_sistema/manual_ayuda_propietario')
DOCUMENTATION_HTML_ROOT_PROPIETARIO = os.path.join(BASE_DIR, 'documentacion_sistema/manual_ayuda_propietario', 'build' ,'html')

DOCUMENTATION_ROOT_PROFESIONAL = os.path.join(BASE_DIR, 'documentacion_sistema/manual_ayuda_profesional')
DOCUMENTATION_HTML_ROOT_PROFESIONAL = os.path.join(BASE_DIR, 'documentacion_sistema/manual_ayuda_profesional', 'build' ,'html')

DOCUMENTATION_ROOT_ADMINISTRATIVO = os.path.join(BASE_DIR, 'documentacion_sistema/manual_ayuda_administrativo')
DOCUMENTATION_HTML_ROOT_ADMINISTRATIVO = os.path.join(BASE_DIR, 'documentacion_sistema/manual_ayuda_administrativo', 'build' ,'html')

DOCUMENTATION_ROOT_VISADOR = os.path.join(BASE_DIR, 'documentacion_sistema/manual_ayuda_visador')
DOCUMENTATION_HTML_ROOT_VISADOR = os.path.join(BASE_DIR, 'documentacion_sistema/manual_ayuda_visador', 'build' ,'html')

DOCUMENTATION_ROOT_INSPECTOR = os.path.join(BASE_DIR, 'documentacion_sistema/manual_ayuda_inspector')
DOCUMENTATION_HTML_ROOT_INSPECTOR = os.path.join(BASE_DIR, 'documentacion_sistema/manual_ayuda_inspector', 'build' ,'html')

DOCUMENTATION_ROOT_DIRECTOR = os.path.join(BASE_DIR, 'documentacion_sistema/manual_ayuda_director')
DOCUMENTATION_HTML_ROOT_DIRECTOR = os.path.join(BASE_DIR, 'documentacion_sistema/manual_ayuda_director', 'build' ,'html')

DOCUMENTATION_ROOT_JEFEINSPECTOR = os.path.join(BASE_DIR, 'documentacion_sistema/manual_ayuda_jefeinspector')
DOCUMENTATION_HTML_ROOT_JEFEINSPECTOR = os.path.join(BASE_DIR, 'documentacion_sistema/manual_ayuda_jefeinspector', 'build' ,'html')

DOCUMENTATION_ROOT_INDICE = os.path.join(BASE_DIR, 'documentacion_sistema/manual_indice')
DOCUMENTATION_HTML_ROOT_INDICE = os.path.join(BASE_DIR, 'documentacion_sistema/manual_indice', 'build' ,'html')
