# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramite', '__first__'),
        ('tipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos.TipoDocumento')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='tramite.Tramite')),
            ],
        ),
    ]
