# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='file',
            field=models.FileField(default=0, upload_to=b'documentos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
