# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField()),
                ('fecha_alta', models.DateTimeField()),
                ('fecha_baja', models.DateTimeField()),
            ],
        ),
    ]
