# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField()),
                ('fecha_alta', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('requerido', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TipoObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('categorias', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
