# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos', '0003_auto_20161006_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
