# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos', '0004_auto_20161006_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoobra',
            name='categoria',
        ),
        migrations.AddField(
            model_name='tipoobra',
            name='categorias',
            field=models.CommaSeparatedIntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
