from django.conf import settings
import os

DOCUMENTATION_ROOT_PROPIETARIO= getattr(settings, 'DOCUMENTATION_ROOT_PROPIETARIO', None)
DOCUMENTATION_ROOT_PROFESIONAL= getattr(settings, 'DOCUMENTATION_ROOT_PROFESIONAL', None)
DOCUMENTATION_ROOT_ADMINISTRATIVO= getattr(settings, 'DOCUMENTATION_ROOT_ADMINISTRATIVO', None)
DOCUMENTATION_ROOT_VISADOR= getattr(settings, 'DOCUMENTATION_ROOT_VISADOR', None)
DOCUMENTATION_ROOT_INSPECTOR= getattr(settings, 'DOCUMENTATION_ROOT_INSPECTOR', None)
DOCUMENTATION_ROOT_DIRECTOR= getattr(settings, 'DOCUMENTATION_ROOT_DIRECTOR', None)
DOCUMENTATION_ROOT_JEFEINSPECTOR= getattr(settings, 'DOCUMENTATION_ROOT_JEFEINSPECTOR', None)
DOCUMENTATION_ROOT_INDICE= getattr(settings, 'DOCUMENTATION_ROOT_INDICE', None)

DOCUMENTATION_ACCESS_FUNCTION = getattr(settings,'DOCUMENTATION_ACCESS_FUNCTION', None)

'''
if not DOCUMENTATION_ROOT_AGENTE or not DOCUMENTATION_ROOT_ADMINISTRADOR or not DOCUMENTATION_ROOT_ADMINISTRADOR_GRAL:
    raise Exception('Please configure DOCUMENTATION_ROOT\'s')
if not DOCUMENTATION_ACCESS_FUNCTION:
    raise Exception('Please configure DOCUMENTATION_ACCESS_FUNCTION')
'''

DOCUMENTATION_HTML_ROOT_PROPIETARIO = getattr(settings,'DOCUMENTATION_HTML_ROOT_PROPIETARIO',os.path.join(DOCUMENTATION_ROOT_PROPIETARIO, '_build/html/'))
DOCUMENTATION_HTML_ROOT_PROFESIONAL = getattr(settings,'DOCUMENTATION_HTML_ROOT_PROFESIONAL',os.path.join(DOCUMENTATION_ROOT_PROFESIONAL, '_build/html/'))
DOCUMENTATION_HTML_ROOT_ADMINISTRATIVO = getattr(settings,'DOCUMENTATION_HTML_ROOT_ADMINISTRATIVO',os.path.join(DOCUMENTATION_ROOT_ADMINISTRATIVO, '_build/html/'))
DOCUMENTATION_HTML_ROOT_VISADOR = getattr(settings,'DOCUMENTATION_HTML_ROOT_VISADOR',os.path.join(DOCUMENTATION_ROOT_VISADOR, '_build/html/'))
DOCUMENTATION_HTML_ROOT_INSPECTOR = getattr(settings,'DOCUMENTATION_HTML_ROOT_INSPECTOR',os.path.join(DOCUMENTATION_ROOT_INSPECTOR, '_build/html/'))
DOCUMENTATION_HTML_ROOT_DIRECTOR = getattr(settings,'DOCUMENTATION_HTML_ROOT_DIRECTOR',os.path.join(DOCUMENTATION_ROOT_DIRECTOR, '_build/html/'))
DOCUMENTATION_HTML_ROOT_JEFEINSPECTOR = getattr(settings,'DOCUMENTATION_HTML_ROOT_JEFEINSPECTOR',os.path.join(DOCUMENTATION_ROOT_JEFEINSPECTOR, '_build/html/'))
DOCUMENTATION_HTML_ROOT_INDICE = getattr(settings,'DOCUMENTATION_HTML_ROOT_INDICE',os.path.join(DOCUMENTATION_ROOT_INDICE, '_build/html/'))



DOCUMENTATION_XSENDFILE = getattr(settings,'DOCUMENTATION_XSENDFILE', not settings.DEBUG)
