# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=20)),
                ('cuil', models.CharField(max_length=14)),
                ('domicilio', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.Rol')),
                ('matricula', models.CharField(max_length=10)),
                ('categoria', models.IntegerField()),
            ],
            bases=('persona.rol',),
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.Rol')),
            ],
            bases=('persona.rol',),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.Rol')),
                ('nombre_de_usuario', models.CharField(max_length=15)),
                ('contrasenia', models.CharField(max_length=15)),
            ],
            bases=('persona.rol',),
        ),
        migrations.AddField(
            model_name='rol',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
    ]
