# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Categoria 1'), (2, 'Categoria 2'), (3, 'Categoria 3')]),
        ),
    ]
