# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20161025_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='certificado',
            field=models.ImageField(null=True, upload_to='certificado/'),
        ),
    ]
