# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_remove_profesional_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='certificado',
            field=models.ImageField(null=True, upload_to='certificado/'),
        ),
    ]
