# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        ('tipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aceptado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tramite.Estado')),
            ],
            bases=('tramite.estado',),
        ),
        migrations.CreateModel(
            name='Agendado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tramite.Estado')),
            ],
            bases=('tramite.estado',),
        ),
        migrations.CreateModel(
            name='Corregido',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tramite.Estado')),
            ],
            bases=('tramite.estado',),
        ),
        migrations.CreateModel(
            name='Finalizado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tramite.Estado')),
            ],
            bases=('tramite.estado',),
        ),
        migrations.CreateModel(
            name='Iniciado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tramite.Estado')),
            ],
            bases=('tramite.estado',),
        ),
        migrations.CreateModel(
            name='Inspeccionado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tramite.Estado')),
            ],
            bases=('tramite.estado',),
        ),
        migrations.CreateModel(
            name='Visado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tramite.Estado')),
                ('monto', models.IntegerField()),
            ],
            bases=('tramite.estado',),
        ),
        migrations.AddField(
            model_name='tramite',
            name='estados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramite.Estado'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='profesional',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.Profesional'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='propietario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.Propietario'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='tipoObra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tipos.TipoObra'),
        ),
    ]
