# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='estados',
        ),
    ]
