# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0002_remove_tramite_estados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='profesional',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='propietario',
        ),
    ]
