# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        ('tramite', '0003_auto_20161110_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='propietario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.Propietario'),
        ),
    ]
