# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        ('tipos', '0002_auto_20161110_2214'),
        ('tramite', '0004_tramite_propietario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='estado',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='tipoObra',
        ),
        migrations.AddField(
            model_name='corregido',
            name='observacion',
            field=models.CharField(default='En este momento no se poseen observaciones sobre el tramite', max_length=100),
        ),
        migrations.AddField(
            model_name='estado',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='tramite',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='tramite.Tramite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iniciado',
            name='observacion',
            field=models.CharField(default='En este momento no se poseen observaciones sobre el tramite', max_length=100),
        ),
        migrations.AddField(
            model_name='tramite',
            name='profesional',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='persona.Profesional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tramite',
            name='tipo_obra',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tipos.TipoObra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visado',
            name='permiso',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visado',
            name='monto',
            field=models.FloatField(),
        ),
    ]
